### ISSUE TITLE
[Macro] Unclear error message

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/firmware#1095]
When you add in `PRODUCT_VERSION();` without `PRODUCT_ID()`, the error message is:

```
usr/local/gcc-arm-embedded-gcc-arm-none-eabi-4_8-2014q2-20140609-linux-tar-bz2/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld: module info static details not linked
collect2: error: ld returned 1 exit status
make: *** [460049fa5b6b3872c0e4cb70ffc613fc9d2c3e5ee23ad8f2d0930f057657.elf] Error 1
```

which doesn't help with fixing the error. Either we edit the docs to mention that BOTH macro must be used in tandem or see how we can make it throw a proper error.

Test app:

```
PRODUCT_VERSION(1);

void setup() {
}

void loop() {
}
```

**Device:** Photon
**System firmware:** 0.5.2

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by technobly** [comment]
Something to note, this issue is present on PHOTON, P1 and ELECTRON, but not CORE.
