### ISSUE TITLE
0.8.0-rc.1 Photon: Particle.connected does not sense lost internet

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/firmware#1479]
## Bug Report
I've got my Photon connected to an AP which in  turn is connected to a cable modem to hook onto the internet. When powering down the AP connection loss is detected virtually immediately and after switching the AP back on connection is reestablished.
But when powering down the cable modem so that the WiFi connection persists, the device never stops breathing cyan and `Particle.connected()` keeps returning `true`.
Even worse, even after switching the cable modem back on, the connection will never be reestablished, since the system doesn't see need for it.

Up to 0.7.0-rc.6 things worked as expected.

### Test App

```c
SYSTEM_MODE(SEMI_AUTOMATIC)
SYSTEM_THREAD(ENABLED)

void setup() {
    WiFi.on();
    Particle.connect();
    pinMode(D7, OUTPUT);
}

void loop() {
    digitalWrite(D7, Particle.connected());
}
```

**Comment by elcojacobs** [comment]
I wanted to try whether the behavior was still present on 0.8.0-rc.2. But for good measure, I first tried it on 0.7.0-rc.6 and got an SOS when I switched the WiFi channel. Wow.

My test against 0.8.0-rc.2 showed correct behavior (RGB LED status and D7 status).

**Comment by elcojacobs** [comment]
Misunderstood the bug, you have 2 modems and are not taking down WiFi, just Internet.
When I unplug the WAN cable from my router, the photon is indeed unaware on 0.8.0-rc.1. Bug confirmed.

When I try the same on 0.8.0-rc.2, same result.
