### ISSUE TITLE
have issue to compile system firmware 0.7.0-r6 

### ISSUE THREAD

**Issue by aeris-ming** [particle-iot/firmware#1483]
/opt/gcc-arm-spark/gcc-arm-none-eabi-5_4-2016q3/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: static RAM use exceeds allocated space
/opt/gcc-arm-spark/gcc-arm-none-eabi-5_4-2016q3/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `APP_FLASH' overflowed by 344 bytes
/opt/gcc-arm-spark/gcc-arm-none-eabi-5_4-2016q3/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `SRAM' overflowed by 16 bytes

**Comment by m-mcgowan** [comment]
gcc 5.4.1 is not supported at present. Please use version 5.3.1. Thanks!

**Comment by aeris-ming** [comment]
@m-mcgowan It works,Thanks very much
