### ISSUE TITLE
Please change the behavior of Serial.write()

### ISSUE THREAD

**Issue by aeris-ming** [particle-iot/firmware#1499]
Now Serial.wrtie() will block or over overwritten.
It will be very nice if Serial.write() write as much as possible and then return the number of bytes written without any block.

**Comment by m-mcgowan** [comment]
Have you seen `availableForWrite()`? It tells you how many characters can be written without blocking. https://docs.particle.io/reference/firmware/photon/#availableforwrite-

**Comment by dmiddlecamp** [comment]
Isn't this behavior also configurable? -> https://docs.particle.io/reference/firmware/electron/#blockonoverrun-

**Comment by aeris-ming** [comment]
@m-mcgowan I think it is not a bad idea if Serial.write() can support it,So user do not have to write their own function and I think it will be easy to handle race condition too.
static int32_t uart1_write(uint8_t *buffer, int32_t size, int32_t id)
{
        int32_t aw = Serial1.availableForWrite();
        aw = (size >= aw) ? aw : size;

        return Serial1.write(buffer, aw);
}

**Comment by aeris-ming** [comment]
it seems no more people support it
