### ISSUE TITLE
dependencies.md lists  brew install gcc-arm-none-eabi-53

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/firmware#1515]
dependencies.md recommend the command:

    brew install gcc-arm-none-eabi-53

53 no longer appears to be available from the PX4 tap, I used 54 instead, can we update the docs to reflect what's available?  Or are these commands working for others on a fresh install?

**Comment by technobly** [comment]
Thanks! Updated here: https://github.com/particle-iot/firmware/commit/29a616f2383d01953c380b3f122ea0cf0fdd1da3
