### ISSUE TITLE
Listen Mode unable to save credentials

### ISSUE THREAD

**Issue by jenschr** [particle-iot/firmware#1550]
### Expected Behavior

Listen mode should allow you to set wifi credentials.

### Observed Behavior

Upon saving credentials via CLI, we receive serial errors and messages telling that wifi credentials could not be saved. When setting up wifi from App (both Android/iOS), the app just hangs at various stages in the setup process.

### Steps to Reproduce

Tested and reproduced on 0.70 and 0.80r4. The problem is 100% repeatable, but only manifests itself when using the firmware for our commercial product. We cannot ship the product to customers with this bug present as they will never be able to setup wifi on their device.

### Test App

We can not post the code publicly, but a verified Particle representative can contact https://community.particle.io/u/jenschr/ to get a copy of the source. We have tried to compile smaller versions of the codebase, but have not been able to reproduce the bug using this.

### References

Ref this forum thread: https://community.particle.io/t/listen-mode-possible-bug/42423/5 See video in this post for a visual description of the bug.

Also some error messages listed in this thread: https://community.particle.io/t/p1-setup-fails-on-app-cli-interactive-listen-mode/42308/4

**Comment by fitchn** [comment]
I've recently seen similar behavior in an application that was running low on RAM.  Listening mode in 0.7.0 seems to use ~20kB of dynamically allocated RAM (!) and we observed no saving of wifi credentials (followed by safe mode entry) when attempting to load credentials via our own app/discovery.  This ended up being extremely difficult to troubleshoot but you can query your current (minimum) free RAM via  System.freeMemory().

**Comment by jenschr** [comment]
@fitchn yeah. If you check the end of the community thread above, @bsatrom  concluded that the problem happens at around 21496 bytes. He'll add this to the docs and then probably close this issue 👍

**Comment by bsatrom** [comment]
Thanks @jenschr I am working on some content to add to the docs now, and will post here and close the issues once I have that.

**Comment by bsatrom** [comment]
Docs have been updated, thanks again @jenschr!
