### ISSUE TITLE
Required dependency gcc-arm 5.3.1 not available in homebrew

### ISSUE THREAD

**Issue by dokterbob** [particle-iot/firmware#1561]
### Expected Behavior

Instructions in [dependencies](https://github.com/particle-iot/firmware/blob/develop/docs/dependencies.md) should allow all required dependendencies, specifically the required version of gcc-arm to be installed.

### Observed Behavior

The earliest 5.* gcc available is 5.4 - gcc-arm 5.3 is not available.

### Steps to Reproduce

```
$ brew uninstall gcc-arm-none-eabi && brew install gcc-arm-none-eabi-53
Uninstalling /usr/local/Cellar/gcc-arm-none-eabi/20171218... (5,633 files, 466.7MB)
Error: No available formula with the name "gcc-arm-none-eabi-53" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

### Suggestion

Officially support gcc-arm 5.4 and update documentation.

**Comment by rickkas7** [comment]
The gcc-arm local build FAQ includes installation instructions not using Homebrew, which allow 5.3.1 to be installed:

https://docs.particle.io/faq/particle-tools/local-build/

**Comment by technobly** [comment]
@dokterbob Thanks for the heads up on this, we really need to maintain our own brew formulas.  In the meantime, I have updated the docs in `develop` to show you how to install gcc 5.3.1 with homebrew: https://github.com/particle-iot/firmware/blob/108538861cd6ddecc12565b0e7662dc4fa3d8c06/docs/dependencies.md

Please let us know if this works for you, so we can close this issue.  Thanks!

**Comment by technobly** [comment]
Closing... please re-open if you find the updated Docs not sufficient.
