### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shreyasnagare** [particle-iot/firmware#1579]
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please choose one of the following templates **Bug Report** or **Feature/Enhancement Request** and delete the other.

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

### Expected Behavior

What should it do?

### Observed Behavior

What did it actually do?

### Steps to Reproduce

How did you make it do that, and which system/user firmware versions were tested?

### Test App

```c
void setup() {
  // A minimal test case to reproduce the issue is super helpful!
}

void loop() {

}
```

### References

Links to the Community, Docs, Other Issues, etc..

---

## Feature/Enhancement Request

Please describe your use case in as much detail as possible. Background information and detailing what the feature will enable you to do, is especially helpful.

**Comment by m-mcgowan** [comment]
Hello @shreyasnagare. For general help, please sign up to our community forum at community.particle.io - you may find your question has already been answered there, or you can describe what you need help with and the community will help you out.
