### ISSUE TITLE
Enable Wire1 for Argon and Xenon

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/firmware#1630]
## Bug Report

`Wire1` should be available for Argon and Xenon

### Observed Behavior

`Wire1` is not declare in this scope when compiling a user firmware fore Argon and Xenon

As per this commit, we should do the same for Argon or Xenon, or even better, for Mesh devices instead: https://github.com/particle-iot/firmware/commit/b014059ef738e45a3a7b0aac2a38a5cf71af56eb

### Steps to Reproduce

Compile an app using `Wire1.xxx`

### Test App

```c
void setup() {
  Wire1.begin()
}

void loop() {

}
```

### References

- https://community.particle.io/t/argon-compile-error/46091

**Comment by avtolstoy** [comment]
Thanks for the report! I can confirm that this was an oversight and we should define `HAL_PLATFORM_I2C2` for Argon and Xenon, which in turn will enable `Wiring_Wire1`.

**Comment by technobly** [comment]
Re-opening since this issue persists with 0.8.0-rc.26 https://community.particle.io/t/wire1-still-not-compiling-on-rc26/46258/4

**Comment by avtolstoy** [comment]
I think this is some kind of a buildpack issue. It builds locally just fine.

**Comment by technobly** [comment]
More info: It does compile on Boron, but not Xenon or Argon.

**Comment by avtolstoy** [comment]
In that case you are targeting rc.25 for some reason, because that's the release that has `Wire1` enabled on Borons and not on Argons and Xenons.
